#!/bin/bash
# Master build script for affiliate sites batch 1
# Generates all HTML, deploys to GitHub, sets DNS, submits IndexNow

GITHUB_PAT="${GH_TOKEN:-$(git -C /home/ubuntu/.openclaw/workspace/swalmy.com remote get-url origin | sed -n 's#https://\(ghp_[^@]*\)@github.com/.*#\1#p')}"
GITHUB_ORG="Brazenproducts"
INDEXNOW_KEY="b4f7e2a1c3d5e6f7a8b9c0d1e2f3a4b5"
AMAZON_TAG="brazenprodu01-20"
BASE="/home/ubuntu/.openclaw/workspace/affiliate-sites"

echo "Build script ready. Sites will be generated by individual scripts."
